// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/register": {
            "post": {
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Auth"],
                "summary": "Register new student",
                "parameters": [
                    {
                        "description": "Register request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {"description": "Student created successfully"},
                    "400": {"description": "Bad request"},
                    "409": {"description": "Email already exists"}
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Auth"],
                "summary": "Login student",
                "description": "Login and receive JWT token. Response includes student_id (MSSV)",
                "parameters": [
                    {
                        "description": "Login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {"description": "Login successful"},
                    "401": {"description": "Invalid credentials"},
                    "403": {"description": "Account inactive"}
                }
            }
        },
        "/api/auth/me": {
            "get": {
                "security": [{"BearerAuth": []}],
                "produces": ["application/json"],
                "tags": ["Auth"],
                "summary": "Get current student info",
                "responses": {
                    "200": {"description": "Current student info"},
                    "401": {"description": "Unauthorized"}
                }
            }
        },
        "/api/students": {
            "get": {
                "security": [{"BearerAuth": []}],
                "produces": ["application/json"],
                "tags": ["Students"],
                "summary": "Get all students (admin only)",
                "parameters": [
                    {"type": "integer", "default": 1, "name": "page", "in": "query"},
                    {"type": "integer", "default": 10, "name": "limit", "in": "query"},
                    {"type": "string", "name": "search", "in": "query"}
                ],
                "responses": {
                    "200": {"description": "List of students"},
                    "403": {"description": "Admin access required"}
                }
            }
        },
        "/api/students/{id}": {
            "get": {
                "security": [{"BearerAuth": []}],
                "produces": ["application/json"],
                "tags": ["Students"],
                "summary": "Get student by ID",
                "parameters": [
                    {"type": "integer", "name": "id", "in": "path", "required": true}
                ],
                "responses": {
                    "200": {"description": "Student details"},
                    "403": {"description": "Access denied"},
                    "404": {"description": "Student not found"}
                }
            },
            "put": {
                "security": [{"BearerAuth": []}],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Students"],
                "summary": "Update student",
                "parameters": [
                    {"type": "integer", "name": "id", "in": "path", "required": true},
                    {"description": "Update request", "name": "request", "in": "body", "required": true, "schema": {"$ref": "#/definitions/dto.UpdateStudentRequest"}}
                ],
                "responses": {
                    "200": {"description": "Student updated"},
                    "403": {"description": "Access denied"},
                    "404": {"description": "Student not found"}
                }
            }
        },
        "/api/students/{id}/enrollments": {
            "get": {
                "security": [{"BearerAuth": []}],
                "produces": ["application/json"],
                "tags": ["Enrollments"],
                "summary": "Get student enrollments",
                "parameters": [
                    {"type": "integer", "name": "id", "in": "path", "required": true},
                    {"type": "string", "name": "status", "in": "query", "description": "Filter by status"},
                    {"type": "integer", "default": 1, "name": "page", "in": "query"},
                    {"type": "integer", "default": 10, "name": "limit", "in": "query"}
                ],
                "responses": {
                    "200": {"description": "List of enrollments"},
                    "403": {"description": "Access denied"}
                }
            }
        },
        "/api/courses": {
            "get": {
                "produces": ["application/json"],
                "tags": ["Courses"],
                "summary": "Get all courses",
                "parameters": [
                    {"type": "integer", "default": 1, "name": "page", "in": "query"},
                    {"type": "integer", "default": 10, "name": "limit", "in": "query"},
                    {"type": "string", "name": "search", "in": "query"},
                    {"type": "string", "name": "category", "in": "query", "description": "Programming, Design, Business, Language, Music"},
                    {"type": "string", "name": "level", "in": "query", "description": "Beginner, Intermediate, Advanced"},
                    {"type": "number", "name": "min_price", "in": "query"},
                    {"type": "number", "name": "max_price", "in": "query"},
                    {"type": "boolean", "default": true, "name": "published_only", "in": "query"}
                ],
                "responses": {
                    "200": {"description": "List of courses"}
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Courses"],
                "summary": "Create course (admin only)",
                "parameters": [
                    {"description": "Create request", "name": "request", "in": "body", "required": true, "schema": {"$ref": "#/definitions/dto.CreateCourseRequest"}}
                ],
                "responses": {
                    "201": {"description": "Course created"},
                    "400": {"description": "Invalid request"},
                    "403": {"description": "Admin access required"}
                }
            }
        },
        "/api/courses/{id}": {
            "get": {
                "produces": ["application/json"],
                "tags": ["Courses"],
                "summary": "Get course by ID with lessons",
                "parameters": [
                    {"type": "integer", "name": "id", "in": "path", "required": true}
                ],
                "responses": {
                    "200": {"description": "Course details with lessons"},
                    "404": {"description": "Course not found"}
                }
            },
            "put": {
                "security": [{"BearerAuth": []}],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Courses"],
                "summary": "Update course (admin only)",
                "parameters": [
                    {"type": "integer", "name": "id", "in": "path", "required": true},
                    {"description": "Update request", "name": "request", "in": "body", "required": true, "schema": {"$ref": "#/definitions/dto.UpdateCourseRequest"}}
                ],
                "responses": {
                    "200": {"description": "Course updated"},
                    "403": {"description": "Admin access required"},
                    "404": {"description": "Course not found"}
                }
            },
            "delete": {
                "security": [{"BearerAuth": []}],
                "tags": ["Courses"],
                "summary": "Delete course (admin only)",
                "parameters": [
                    {"type": "integer", "name": "id", "in": "path", "required": true}
                ],
                "responses": {
                    "200": {"description": "Course deleted"},
                    "403": {"description": "Admin access required"},
                    "404": {"description": "Course not found"},
                    "409": {"description": "Course has active enrollments"}
                }
            }
        },
        "/api/courses/{id}/lessons": {
            "post": {
                "security": [{"BearerAuth": []}],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Courses"],
                "summary": "Add lesson to course (admin only)",
                "parameters": [
                    {"type": "integer", "name": "id", "in": "path", "required": true},
                    {"description": "Lesson request", "name": "request", "in": "body", "required": true, "schema": {"$ref": "#/definitions/dto.CreateLessonRequest"}}
                ],
                "responses": {
                    "201": {"description": "Lesson added"},
                    "403": {"description": "Admin access required"},
                    "404": {"description": "Course not found"}
                }
            }
        },
        "/api/courses/{id}/enrollments": {
            "get": {
                "security": [{"BearerAuth": []}],
                "produces": ["application/json"],
                "tags": ["Enrollments"],
                "summary": "Get course enrollments (admin only)",
                "parameters": [
                    {"type": "integer", "name": "id", "in": "path", "required": true},
                    {"type": "integer", "default": 1, "name": "page", "in": "query"},
                    {"type": "integer", "default": 10, "name": "limit", "in": "query"}
                ],
                "responses": {
                    "200": {"description": "List of enrollments"},
                    "403": {"description": "Admin access required"},
                    "404": {"description": "Course not found"}
                }
            }
        },
        "/api/enrollments": {
            "post": {
                "security": [{"BearerAuth": []}],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Enrollments"],
                "summary": "Enroll in a course",
                "parameters": [
                    {"description": "Enroll request", "name": "request", "in": "body", "required": true, "schema": {"$ref": "#/definitions/dto.EnrollRequest"}}
                ],
                "responses": {
                    "201": {"description": "Enrolled successfully"},
                    "404": {"description": "Course not found"},
                    "409": {"description": "Already enrolled"}
                }
            }
        },
        "/api/enrollments/{id}/progress": {
            "get": {
                "security": [{"BearerAuth": []}],
                "produces": ["application/json"],
                "tags": ["Enrollments"],
                "summary": "Get enrollment progress",
                "parameters": [
                    {"type": "integer", "name": "id", "in": "path", "required": true}
                ],
                "responses": {
                    "200": {"description": "Detailed progress"},
                    "403": {"description": "Access denied"},
                    "404": {"description": "Enrollment not found"}
                }
            }
        },
        "/api/enrollments/{id}/lessons/{lesson_id}/complete": {
            "put": {
                "security": [{"BearerAuth": []}],
                "tags": ["Enrollments"],
                "summary": "Mark lesson as completed",
                "parameters": [
                    {"type": "integer", "name": "id", "in": "path", "required": true},
                    {"type": "integer", "name": "lesson_id", "in": "path", "required": true}
                ],
                "responses": {
                    "200": {"description": "Lesson completed"},
                    "403": {"description": "Access denied"},
                    "404": {"description": "Not found"},
                    "409": {"description": "Already completed or dropped"}
                }
            }
        },
        "/api/enrollments/{id}": {
            "delete": {
                "security": [{"BearerAuth": []}],
                "tags": ["Enrollments"],
                "summary": "Drop enrollment",
                "parameters": [
                    {"type": "integer", "name": "id", "in": "path", "required": true}
                ],
                "responses": {
                    "200": {"description": "Enrollment dropped"},
                    "403": {"description": "Access denied"},
                    "404": {"description": "Enrollment not found"},
                    "409": {"description": "Already dropped"}
                }
            }
        }
    },
    "definitions": {
        "dto.RegisterRequest": {
            "type": "object",
            "required": ["email", "password", "full_name"],
            "properties": {
                "email": {"type": "string", "example": "student@example.com"},
                "password": {"type": "string", "minLength": 6, "example": "password123"},
                "full_name": {"type": "string", "example": "Nguyễn Văn A"},
                "phone_number": {"type": "string", "example": "0123456789"},
                "date_of_birth": {"type": "string", "example": "2000-01-01"},
                "gender": {"type": "string", "enum": ["male", "female", "other"]}
            }
        },
        "dto.LoginRequest": {
            "type": "object",
            "required": ["email", "password"],
            "properties": {
                "email": {"type": "string", "example": "student@example.com"},
                "password": {"type": "string", "example": "password123"}
            }
        },
        "dto.UpdateStudentRequest": {
            "type": "object",
            "properties": {
                "full_name": {"type": "string"},
                "phone_number": {"type": "string"},
                "date_of_birth": {"type": "string"},
                "gender": {"type": "string", "enum": ["male", "female", "other"]},
                "avatar_url": {"type": "string"},
                "is_active": {"type": "boolean", "description": "Admin only"}
            }
        },
        "dto.CreateCourseRequest": {
            "type": "object",
            "required": ["title", "instructor", "category", "level", "price"],
            "properties": {
                "title": {"type": "string", "example": "Flutter Development"},
                "description": {"type": "string"},
                "instructor": {"type": "string", "example": "John Doe"},
                "category": {"type": "string", "enum": ["Programming", "Design", "Business", "Language", "Music"]},
                "level": {"type": "string", "enum": ["Beginner", "Intermediate", "Advanced"]},
                "duration": {"type": "integer", "example": 40},
                "price": {"type": "number", "example": 500000},
                "image_url": {"type": "string"}
            }
        },
        "dto.UpdateCourseRequest": {
            "type": "object",
            "properties": {
                "title": {"type": "string"},
                "description": {"type": "string"},
                "instructor": {"type": "string"},
                "category": {"type": "string"},
                "level": {"type": "string"},
                "duration": {"type": "integer"},
                "price": {"type": "number"},
                "image_url": {"type": "string"},
                "is_published": {"type": "boolean"}
            }
        },
        "dto.CreateLessonRequest": {
            "type": "object",
            "required": ["title"],
            "properties": {
                "title": {"type": "string", "example": "Introduction to Flutter"},
                "description": {"type": "string"},
                "video_url": {"type": "string"},
                "duration": {"type": "integer", "example": 30},
                "order": {"type": "integer", "example": 1}
            }
        },
        "dto.EnrollRequest": {
            "type": "object",
            "required": ["course_id"],
            "properties": {
                "course_id": {"type": "integer", "example": 1}
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "Enter: Bearer {token}"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Online Learning Management API",
	Description:      "RESTful API for Online Learning Management System - Hệ thống quản lý học online",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
